maglnet/ComposerRequireChecker

.travis.yml
Adds the latest-version to the tested versions on travis. Therefore the latest "nightly" is also tested along with the current stable release
=> Adds latest PHP to checked versions

src/ComposerRequireChecker/Cli/CheckCommand.php, src/ComposerRequireChecker/DependencyGuesser/DependencyGuesser.php, src/ComposerRequireChecker/DependencyGuesser/GuessFromLoadedExtensions.php, src/ComposerRequireChecker/DependencyGuesser/GuesserInterface.php, test/ComposerRequireCheckerTest/DependencyGuesser/DependencyGuesserTest.php
As mentioned in #2, it would be nice to see, which dependency should be required to fix an unknown symbol.
This draft checks all loaded extensions for the unknown symbol and suggests requiring an extension if it can be found.
=> [WIP] first draft to suggest requiring of extensions

.travis.yml, README.md, bin/composer-require-checker.php, composer.json, test/travis-composer.json
It allows to install this package globally by `composer global require maglnet/composer-require-checker` and use the checker as any other command (if `$COMPOSER_HOME/vendor/bin` is added to `$PATH`).
=> Added bin/composer-require-checker to Composer-managed binaries list

data/config.dist.json, src/ComposerRequireChecker/Cli/Options.php
Adding `callable` and PHP 7.1's `iterable` and `void` types to whitelisted symbols.
=> Add missing symbols to whitelist

src/ComposerRequireChecker/FileLocator/LocateComposerPackageSourceFiles.php, test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageSourceFilesTest.php
The `{"autoload": {"psr-0|psr-4": {"MyNamespace": ["src", "lib"]}}}` format doesn't work at the moment.
This tries to fix that, but the tests are still failing at the moment and I can't figure out why.
Also, I'm not sure if the `array_reduce()` method is the clearest way to write this, but I tried to follow the functional style of the existing code.
Can someone figure out what's wrong?
=> Handle composer autoload directories as arrays correctly

src/ComposerRequireChecker/FileLocator/LocateAllFilesByExtension.php, test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageSourceFilesTest.php
Hi and thanks for this great tool! 
With the latest version (which adds exclude-from-classpath support), I observed an common errors like this:
```
Warning: preg_match(): Compilation failed: nothing to repeat at offset 1 in phar:///.../composer-require-checker.phar/src/ComposerRequireChecker/FileLocator/LocateAllFilesByExtension.php on line 29
```
This is because `exclude-from-classpath` [can](https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps) contain `*` and `**` wildcards. For example in Symfony: https://github.com/symfony/symfony/blob/master/composer.json#L125 .
These `*` and `**` sequences obviously breaks the regexp pattern used in LocateAllFilesByExtension.php and causes the mentioned error.
This PR adds regexp escaping and also supports of the actual wildcards …
=> Fix exclude-from-classpath containing wildcards

composer.json, src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php, test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRootsTest.php, test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorTest.php
=> update php-parser to 4.0

composer.json
There's a [bug](https://github.com/symfony/symfony/issues/28666) in symfony/console 3.4.16 and 4.1.5 where the exit code is reported as success if it failed.
This obviously affects this tool in a major way rendering it useless in a CI environment, so this PR ensures this bug cannot be installed.
=> Prevent using symfony/console with broken exit code handling

src/ComposerRequireChecker/Cli/CheckCommand.php
Loading the composer.json file will throw an exception if the file can't be loaded, so there is no need to load it twice
=> Don't load composer.json file twice

.scrutinizer.yml
=> Fix: Exclude test fixtures from scrutiny of Scrutinizer

.travis.yml
This PR
💁‍♂ For reference, see
* https://travis-ci.org/maglnet/ComposerRequireChecker/jobs/569566549#L224
* https://travis-ci.org/maglnet/ComposerRequireChecker/jobs/569566549#L238
=> Fix: Do not update composer itself twice

test/ComposerRequireCheckerTest/ASTLocator/LocateASTFromFilesTest.php, test/ComposerRequireCheckerTest/BinaryTest.php, test/ComposerRequireCheckerTest/Cli/ApplicationTest.php, test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php, test/ComposerRequireCheckerTest/Cli/OptionsTest.php, test/ComposerRequireCheckerTest/DefinedExtensionsResolver/DefinedExtensionsResolverTest.php, test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRootsTest.php, test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromExtensionsTest.php, test/ComposerRequireCheckerTest/DependencyGuesser/DependencyGuesserTest.php, test/ComposerRequireCheckerTest/FileLocator/LocateAllFilesByExtensionTest.php, test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageDirectDependenciesSourceFilesTest.php, test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageSourceFilesTest.php, test/ComposerRequireCheckerTest/FileLocator/LocateFilesByGlobPatternTest.php, test/ComposerRequireCheckerTest/JsonLoaderTest.php, test/ComposerRequireCheckerTest/NodeVisitor/DefinedSymbolCollectorFunctionalTest.php, test/ComposerRequireCheckerTest/NodeVisitor/DefinedSymbolCollectorTest.php, test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorFunctionalTest.php, test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorTest.php, test/ComposerRequireCheckerTest/UsedSymbolsLocator/LocateUsedSymbolsFromASTRootsTest.php
This PR
💁‍♂ I ran
```
$ composer global require friendsofphp/php-cs-fixer
```
followed by
```
$ php-cs-fixer fix --allow-risky=yes --rules=void_return test
```
=> Enhancement: Add void return type declarations to test methods

test/ComposerRequireCheckerTest/BinaryTest.php, test/ComposerRequireCheckerTest/Cli/ApplicationTest.php, test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php, test/ComposerRequireCheckerTest/DependencyGuesser/DependencyGuesserTest.php, test/ComposerRequireCheckerTest/FileLocator/LocateFilesByGlobPatternTest.php
This PR
💁‍♂ I ran
```
$ composer global require friendsofphp/php-cs-fixer
```
followed by
```
$ php-cs-fixer fix --allow-risky=yes --rules=php_unit_set_up_tear_down_visibility test
```
=> Fix: Reduce visibility of setUp()

.travis.yml, CHANGELOG.md, composer.json
This PR
Related to https://github.com/maglnet/ComposerRequireChecker/pull/126#discussion_r312696453.
=> Fix: Drop support for PHP 7.1

src/ComposerRequireChecker/UsedSymbolsLocator/LocateUsedSymbolsFromASTRoots.php, test/ComposerRequireCheckerTest/UsedSymbolsLocator/LocateUsedSymbolsFromASTRootsTest.php, test/fixtures/unknownSymbols/src/OtherThing.php
This PR
```
The following unknown symbols were found:
+------------------------------------------------------+--------------------+
| unknown symbol                                       | guessed dependency |
+------------------------------------------------------+--------------------+
| Psr\Http\Message\RequestFactoryInterface             |                    |
| Psr\Http\Message\StreamFactoryInterface              |                    |
| Http\Client\HttpClient                               |                    |
| filter_var                                           | ext-filter         |
| FILTER_VALIDATE_URL                                  | ext-filter         |
| Psr\Log\LoggerInterface                              |                    |
| …
```
=> Enhancement: Sort unknown symbols

composer.json, test/ComposerRequireCheckerTest/BinaryTest.php, test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php, test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRootsTest.php, test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromExtensionsTest.php
=> Enhancement: Update phpunit/phpunit

test/ComposerRequireCheckerTest/ASTLocator/LocateASTFromFilesTest.php, test/ComposerRequireCheckerTest/BinaryTest.php, test/ComposerRequireCheckerTest/Cli/ApplicationTest.php, test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php, test/ComposerRequireCheckerTest/Cli/OptionsTest.php, test/ComposerRequireCheckerTest/DefinedExtensionsResolver/DefinedExtensionsResolverTest.php, test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRootsTest.php, test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromExtensionsTest.php, test/ComposerRequireCheckerTest/DependencyGuesser/DependencyGuesserTest.php, test/ComposerRequireCheckerTest/FileLocator/LocateAllFilesByExtensionTest.php, test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageDirectDependenciesSourceFilesTest.php, test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageSourceFilesTest.php, test/ComposerRequireCheckerTest/FileLocator/LocateFilesByGlobPatternTest.php, test/ComposerRequireCheckerTest/JsonLoaderTest.php, test/ComposerRequireCheckerTest/NodeVisitor/DefinedSymbolCollectorTest.php, test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorTest.php, test/ComposerRequireCheckerTest/UsedSymbolsLocator/LocateUsedSymbolsFromASTRootsTest.php
=> Enhancement: Mark test classes as final

phpunit.xml.dist
This PR
💁‍♂ Missed this in #126.
=> Fix: Configure path to PHPUnit result cache file

composer.json
=> Require ext-zend-opcache for development.

test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php
It runs CheckCommand using a source file from the test code, to ensure the check fails. This allows to test the "unknown symbol found" path of the CheckCommand.
=> Test that CheckCommand finds unknown symbols.

composer.json, src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php
I've just added support of symfony's console 5
=> Add support of Symfony Console 5.

README.md
What about an API library containing Guzzle, and then reuse Guzzle without explicit dependency?
=> Explain the indirect dependency thingy

.github/workflows/phar-creation.yml
With this PR we add the possibility to test new features via an automatic phar build created and download able from the CI. With this new stuff can be easy tested on larger projects and without checking out the branch and manually building the phar. WDYT?
=> Test automatic phar creation process
