maglnet/ComposerRequireChecker

- data/config.dist.json
- src/ComposerRequireChecker/Cli/Options.php
This commit adds the first additional extensions that should be
available by default
Those will be the ones mentioned in
http://php.net/manual/en/extensions.membership.php
This addresses #3
> Adds default extensions

- .idea/composerJson.xml
- composer.json
- test/ComposerRequireCheckerTest/ASTLocator/LocateASTFromFilesTest.php
- test/ComposerRequireCheckerTest/DefinedExtensionsResolver/DefinedExtensionsResolverTest.php
- test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRootsTest.php
- test/ComposerRequireCheckerTest/FileLocator/LocateAllFilesByExtensionTest.php
- test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageDirectDependenciesSourceFilesTest.php
- test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageSourceFilesTest.php
- test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorTest.php
- test/ComposerRequireCheckerTest/UsedSymbolsLocator/LocateUsedSymbolsFromASTRootsTest.php
Adding a number of tests to get the coverage closer to 100%.
> Add tests to increase coverage

- .travis.yml
- composer.json
- src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php
- test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRootsTest.php
closes https://github.com/maglnet/ComposerRequireChecker/issues/23
> DefinedSymbolCollector - Filter out anonymous classes.

- CHANGELOG.md
- data/config.dist.json
- src/ComposerRequireChecker/Cli/Options.php
> Phar ext is builtin

- data/config.dist.json
http://php.net/manual/en/phar.installation.php
> Phar ext is built in

- src/ComposerRequireChecker/Cli/CheckCommand.php
- src/ComposerRequireChecker/FileLocator/LocateAllFilesByExtension.php
- src/ComposerRequireChecker/FileLocator/LocateComposerPackageSourceFiles.php
- test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageSourceFilesTest.php
closes https://github.com/maglnet/ComposerRequireChecker/issues/25
> Normalize paths read from composer.json

- .travis.yml
This should fix problems where lines of code and coverage percentage differs slightly between builds
> only run coverage report on php 7.1

- composer.json
> Remove minimum-stability:dev

- src/ComposerRequireChecker/FileLocator/LocateComposerPackageDirectDependenciesSourceFiles.php
- test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageDirectDependenciesSourceFilesTest.php
This addresses the "vendor-dir" part of issue 81.
> Dynamically detect the vendor directory

- README.md
Adds an explanation of what the package tries to solve. Not sure it's perfect, but it should be a starting point… 😉
> Explain purpose of the package, specifically around direct and transitive dependencies

- src/ComposerRequireChecker/DefinedExtensionsResolver/DefinedExtensionsResolver.php
- src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromExtensions.php
- test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromExtensionsTest.php
> ext-Zend Opcache vs ext-zend-opcache in composer

- src/ComposerRequireChecker/Cli/CheckCommand.php
- src/ComposerRequireChecker/FileLocator/LocateComposerPackageDirectDependenciesSourceFiles.php
- src/ComposerRequireChecker/FileLocator/LocateComposerPackageSourceFiles.php
- test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageSourceFilesTest.php
Reduce IO and dependency on `composer.json` in preparation for #105
> Change LocateComposerPackageSourceFiles to require a data structure

- .travis.yml
> Enhancement: Collect coverage only when actually desired

- src/ComposerRequireChecker/Cli/Application.php
- test/ComposerRequireCheckerTest/Cli/OptionsTest.php
> Fix: Remove file headers

- README.md
This PR
Partially related to #127.
> Fix: Badges

- composer.json
> Enhancement: Update phpstan/phpstan

- .dependabot/config.yml
> change update interval to monthly

- appveyor.yml
- bin/composer-require-checker.bat
- src/ComposerRequireChecker/FileLocator/LocateAllFilesByExtension.php
- test/ComposerRequireCheckerTest/BinaryTest.php
- test/ComposerRequireCheckerTest/FileLocator/LocateAllFilesByExtensionTest.php
- test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageSourceFilesTest.php
I have just fixed the tests that were failing on my Windows box.
> Windows compat

- README.md
Based on the discussion in #182
> Explain the install plugin workaround

- .travis.yml
- baseline.xml
- composer.json
- psalm.xml
- src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php
- src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRoots.php
- src/ComposerRequireChecker/FileLocator/LocateFilesByGlobPattern.php
- src/ComposerRequireChecker/GeneratorUtil/ComposeGenerators.php
- src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php
- src/ComposerRequireChecker/UsedSymbolsLocator/LocateUsedSymbolsFromASTRoots.php
- test/ComposerRequireCheckerTest/ASTLocator/LocateASTFromFilesTest.php
- test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorTest.php
I added psalm with level 4.
Still missing is the adjustment for travis. tbd.
> Add Psalm - Level 4

- src/ComposerRequireChecker/FileLocator/LocateFilesByGlobPattern.php
Fixes  #202 and deprecation warning in PHP 8
> Make first parameter of `LocateFilesByGlobPattern#__invoke()` required

- src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php
- test/ComposerRequireCheckerTest/ASTLocator/LocateASTFromFilesTest.php
> Do not parse passed file if it is not a regular file

- README.md
Seems like this issue pops up now and then, see #221 #144.
> Add description how to customize the config file

- .github/workflows/coding-standard.yml
- .github/workflows/phar-creation.yml
- .github/workflows/phpstan.yml
- .github/workflows/phpunit.yml
- .github/workflows/psalm.yml
- .github/workflows/require-checker.yml
- Makes sure correct files are cached on any OS, be it Linux or Windows.
- Adopted [from PHP-CS-Fixer configuration](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/7a1641e253666449407a5645f27ec5295ffa195a/.github/workflows/ci.yml#L73-L86).
> Adopt OS-dependent cache procedure
